import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "./next-toastify.js";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Start",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
