export const imagedata1=[
"./DroneAcharya.jpeg",
"./BigFM.jpeg",
"./Digital terminal .jpeg",
"./Easemytrip.jpeg",
"./Redtape.jpeg",
"./Vermillion.jpeg",
"./Witness manera.jpeg",
"./Gfg.jpeg",
"./2iim.jpeg",
"./Techstory.jpeg",
"./Icici.jpeg",
"./Edustation.jpeg",
]
export const imagedata2=[
"./Knowafest.jpeg",
"./Safeexpress.jpeg",
"./Ananta aspire.jpeg",
"./Dubeat.jpeg",
"./iHub-AWaDH.jpeg",    
"./Gamesncomps.jpeg",
"./Edufabrica.jpeg",
"./Finlatics.jpeg",
"./Vehant.jpeg",
"./Noticebard.jpeg",
"./Rocketrees.jpeg",
"./Algozenith.jpeg",
"./Axenic.jpeg",
]