# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Admin

on:
  push:
    branches: [production]

  pull_request:
    branches: [production]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install 

      - name: Create Build
        run: yarn run build 

      - name: Restart the server
        run: pm2 restart run.sh --name iitrpr
